//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Diagnostico_Pre
    {
        public int ID_Pre_Diagnostico { get; set; }
        public Nullable<int> ID_Inseminacao { get; set; }
        public Nullable<System.DateTime> Data_Pre_Diagnostico { get; set; }
        public Nullable<bool> Score_Pre { get; set; }
        public string Detalhes_Pre { get; set; }
        public string Observacoes_Pre { get; set; }
    
        public virtual Inseminacoes Inseminacoes { get; set; }
    }
}
