//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fazendas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fazendas()
        {
            this.Animais = new HashSet<Animais>();
        }
    
        public int ID_Fazenda { get; set; }
        public string Nome_Fazenda { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> ID_Cidade { get; set; }
        public Nullable<int> ID_Estado { get; set; }
        public Nullable<int> ID_Proprietario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animais> Animais { get; set; }
        public virtual Cidades Cidades { get; set; }
        public virtual Estados Estados { get; set; }
        public virtual Proprietarios Proprietarios { get; set; }
    }
}
