//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tccEntities : DbContext
    {
        public tccEntities()
            : base("name=tccEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animais> Animais { get; set; }
        public virtual DbSet<Cidades> Cidades { get; set; }
        public virtual DbSet<Diagnostico_Pos> Diagnostico_Pos { get; set; }
        public virtual DbSet<Diagnostico_Pre> Diagnostico_Pre { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<Fazendas> Fazendas { get; set; }
        public virtual DbSet<Generos> Generos { get; set; }
        public virtual DbSet<Inseminacoes> Inseminacoes { get; set; }
        public virtual DbSet<Proprietarios> Proprietarios { get; set; }
        public virtual DbSet<Racas> Racas { get; set; }
        public virtual DbSet<Semens> Semens { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
