//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Semens
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Semens()
        {
            this.Inseminacoes = new HashSet<Inseminacoes>();
        }
    
        public int ID_Semen { get; set; }
        public string Nome { get; set; }
        public Nullable<int> Quantidade { get; set; }
        public Nullable<System.DateTime> Data_Validade { get; set; }
        public Nullable<int> ID_Proprietario { get; set; }
    
        public virtual Proprietarios Proprietarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inseminacoes> Inseminacoes { get; set; }
    }
}
